version: '3.8'

services:
  timepulse:
    image: gapp/timepulse
    build:
      context: .
      args:
        ENVIRONMENT: production
    ports:
      - ${PORT:-4100}:3000
    networks:
      - gapp-network
    command:
      [
        'uwsgi',
        '--http',
        '0.0.0.0:3000',
        '--master',
        '--threads',
        '2',
        '-p',
        '2',
        '-w',
        'wsgi:app',
      ]

networks:
  gapp-network:
